services:
  client:
    build:
      context: ./front-end
    ports:
      - "3000:80"
    depends_on:
      - server

  server:
    build:
      context: ./server
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOSTNAME: db
      MYSQL_PORT: 3306
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
    volumes:
      - ./server/src:/app/src
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: moria_desbravadores
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
