package br.com.moria.enums;

public enum TipoMembro {
    DIRETOR_CLUBE,
    DIRETOR_ASSOCIADO,
    TESOUREIRO,
    CAPELAO,
    SECRETARIO,
    INSTRUTOR_CLASSES_PROGRESSIVAS,
    CONSELHEIRO_UNIDADE,
    AUXILIAR,
    DESBRAVADOR,
    RESPONSAVEL
}