export const states = [
    { value: 'acre', label: 'Acre', abbreviation: 'AC' },
    { value: 'alagoas', label: 'Alagoas', abbreviation: 'AL' },
    { value: 'amapa', label: 'Amapá', abbreviation: 'AP' },
    { value: 'amazonas', label: 'Amazonas', abbreviation: 'AM' },
    { value: 'bahia', label: 'Bahia', abbreviation: 'BA' },
    { value: 'ceara', label: 'Ceará', abbreviation: 'CE' },
    { value: 'espirito-santo', label: 'Espírito Santo', abbreviation: 'ES' },
    { value: 'goias', label: 'Goiás', abbreviation: 'GO' },
    { value: 'maranhao', label: 'Maranhão', abbreviation: 'MA' },
    { value: 'mato-grosso', label: 'Mato Grosso', abbreviation: 'MT' },
    { value: 'mato-grosso-do-sul', label: 'Mato Grosso do Sul', abbreviation: 'MS' },
    { value: 'minas-gerais', label: 'Minas Gerais', abbreviation: 'MG' },
    { value: 'para', label: 'Pará', abbreviation: 'PA' },
    { value: 'paraiba', label: 'Paraíba', abbreviation: 'PB' },
    { value: 'parana', label: 'Paraná', abbreviation: 'PR' },
    { value: 'pernambuco', label: 'Pernambuco', abbreviation: 'PE' },
    { value: 'piaui', label: 'Piauí', abbreviation: 'PI' },
    { value: 'rio-de-janeiro', label: 'Rio de Janeiro', abbreviation: 'RJ' },
    { value: 'rio-grande-do-norte', label: 'Rio Grande do Norte', abbreviation: 'RN' },
    { value: 'rio-grande-do-sul', label: 'Rio Grande do Sul', abbreviation: 'RS' },
    { value: 'rondonia', label: 'Rondônia', abbreviation: 'RO' },
    { value: 'roraima', label: 'Roraima', abbreviation: 'RR' },
    { value: 'santa-catarina', label: 'Santa Catarina', abbreviation: 'SC' },
    { value: 'sao-paulo', label: 'São Paulo', abbreviation: 'SP' },
    { value: 'sergipe', label: 'Sergipe', abbreviation: 'SE' },
    { value: 'tocantins', label: 'Tocantins', abbreviation: 'TO' },
    { value: 'distrito-federal', label: 'Distrito Federal', abbreviation: 'DF' },
];